parameters:
    wikp_payment_mtgox.class: Wikp\PaymentMtgoxBundle\Mtgox\Client
    wikp_payment_mtgox.plugin.class: Wikp\PaymentMtgoxBundle\Plugin\MtgoxPaymentPlugin
    wikp_payment_mtgox.order_repository.class: Wikp\PaymentMtgoxBundle\Plugin\OrderRepositoryFactory
    wikp_payment_mtgox.api_key: ~
    wikp_payment_mtgox.api_secret: ~
    wikp_payment_mtgox.order_repository_path: ~
    wikp_payment_mtgox.return_url: null
    wikp_payment_mtgox.cancel_url: null
    wikp_payment_mtgox.debug: true
    wikp_payment_mtgox.current_prices_retriever.class: Wikp\PaymentMtgoxBundle\Mtgox\CurrentPricesRetriever
    wikp_payment_mtgox.exchange.class: Wikp\PaymentMtgoxBundle\Mtgox\Exchange

services:
    wikp_payment_mtgox.client:
        class: %wikp_payment_mtgox.class%
        arguments: [%wikp_payment_mtgox.api_key%, %wikp_payment_mtgox.api_secret%]

    wikp_payment_mtgox.plugin:
        class: %wikp_payment_mtgox.plugin.class%
        public: true
        scope: request
        arguments:
            - %wikp_payment_mtgox.return_url%
            - %wikp_payment_mtgox.cancel_url%
            - @wikp_payment_mtgox.client
            - @form.factory
            - @request

    wikp_payment_mtgox.order_repository:
        class: %wikp_payment_mtgox.order_repository.class%
        arguments:
            - @doctrine.orm.entity_manager
            - %wikp_payment_mtgox.order_repository_path%

    wikp_payment_mtgox.exchange:
        class: %wikp_payment_mtgox.exchange.class%
        arguments:
            - @doctrine.orm.entity_manager

    wikp_payment_mtgox.form.type.ipn:
        class: Wikp\PaymentMtgoxBundle\Form\MtgoxIpnType
        arguments:
            - %wikp_payment_mtgox.api_secret%
        tags:
            - { name: form.type, alias: wikp_mtgox_ipn }

    wikp_payment_mtgox.current_prices_retriever:
        class: %wikp_payment_mtgox.current_prices_retriever.class%
        arguments:
            - @doctrine.orm.entity_manager
            - @wikp_payment_mtgox.client

    wikp_payment_mtgox.stdin_reader:
        class: Wikp\PaymentMtgoxBundle\Util\StandardInputReader
